Repository wecode-bootcamp-korea/10-ok-bujangnim-frontend, pull requests merged in 2020-07, with the labels that each got.

#1 [배정규] Add: FilterBar 레이아웃 완료
  .eslintrc.json
  package-lock.json
  package.json
  public/data/PL.json
  public/data/productlist.json
  public/data/recommend.json
  src/Common.scss
  src/Components/Aesoplogo.js
  src/Components/Aesoplogo.scss
  src/Components/Footer.js
  src/Components/Footer.scss
  src/Components/Nav.js
  src/Components/Nav.scss
  src/Components/Productfilternav.js
  src/Components/Productfilternav.scss
  src/Pages/Product/Components/Recommendproduct.js
  src/Pages/Product/Components/Recommendproduct.scss
  src/Pages/Product/Productdetails.js
  src/Pages/Product/Productdetails.scss
  src/Pages/ProductList/Components/Product.js
  src/Pages/ProductList/Components/Product.scss
  src/Pages/ProductList/Components/Productslider.js
  src/Pages/ProductList/Components/Productslider.scss
  src/Pages/ProductList/Components/Sliderintro.js
  src/Pages/ProductList/Components/Sliderintro.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Pages/ProductList/test.js
  src/Reset.scss
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: Accepted

#2 [최운정] Fix: 충돌해결
  package-lock.json
  package.json
  public/data/maindata.json
  public/data/mockdata.json
  public/data/skindata.json
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/SkinDetail.js
  src/Components/Nav/SkinDetail.scss
  src/Components/Nav/SkinSideBar.js
  src/Components/Nav/SkinSideBar.scss
  src/Components/test.js
  src/Pages/Main/Components/Appointment/Appointment.js
  src/Pages/Main/Components/Appointment/Appointment.scss
  src/Pages/Main/Components/Carousel/Carousel.js
  src/Pages/Main/Components/Carousel/Carousel.scss
  src/Pages/Main/Components/CitrusFeed/CitrusFeed.js
  src/Pages/Main/Components/CitrusFeed/CitrusFeed.scss
  src/Pages/Main/Components/Quote/Quote.js
  src/Pages/Main/Components/Quote/Quote.scss
  src/Pages/Main/Components/Store/Store.js
  src/Pages/Main/Components/Store/Store.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/config.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#3 [송수호]Fix: 컨플릭트 error 수정완료
  .eslintrc.js
  .eslintrc.json
  package-lock.json
  package.json
  public/data/mocup.json
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/Signup.js
  src/Pages/Login/Signup.scss
  src/Pages/Login/test.js
  src/Pages/Product/test.js
  src/Pages/Productmap/Component/Mapgoods.js
  src/Pages/Productmap/Component/Mapgoods.scss
  src/Pages/Productmap/Component/Underbar.js
  src/Pages/Productmap/Component/Underbar.scss
  src/Pages/Productmap/Mapcomponent.js
  src/Pages/Productmap/Mapcomponent.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#6 [배정규] Add: 상품 리스트 페이지 모두 보기 버튼 데이터 추가
  public/data/PD.json
  public/data/PL.json
  src/Components/Footer.js
  src/Components/Productfilternav.js
  src/Pages/Product/Components/OverlayIngredient.js
  src/Pages/Product/Components/OverlayIngredient.scss
  src/Pages/Product/Components/Recommendproduct.js
  src/Pages/Product/Productdetails.js
  src/Pages/Product/Productdetails.scss
  src/Pages/ProductList/Components/Product.js
  src/Pages/ProductList/Components/Productslider.js
  src/Pages/ProductList/Components/Sliderintro.js
  src/Pages/ProductList/ProductList.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#8 [배정규] Add: 상품 리스트 페이지 Url Parameter 기능 구현 완료
  public/data/PDD.json
  src/Common.scss
  src/Components/Productfilternav.js
  src/Components/Productfilternav.scss
  src/Pages/Product/Components/OverlayIngredient.js
  src/Pages/Product/Components/OverlayIngredient.scss
  src/Pages/Product/Productdetails.js
  src/Pages/Product/Productdetails.scss
  src/Pages/ProductList/Components/Product.js
  src/Pages/ProductList/Components/Productslider.js
  src/Pages/ProductList/Components/Productslider.scss
  src/Pages/ProductList/ProductList.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#5 [최운정] Fix: 충돌해결
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/modules.xml
  .idea/workspace.xml
  package-lock.json
  package.json
  public/data/mockdata.json
  public/data/pdexample.json
  public/data/productDetail.json
  public/data/skindata.json
  src/Common.scss
  src/Components/Cart/Cart.js
  src/Components/Cart/Cart.scss
  src/Components/Cart/CartList.js
  src/Components/Cart/CartList.scss
  src/Components/Cart/CartMessage.js
  src/Components/Cart/CartMessage.scss
  src/Components/Cart/CartSum.js
  src/Components/Cart/CartSum.scss
  src/Components/Footer.scss
  src/Components/Nav.js
  src/Components/Nav.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/SkinDetail.js
  src/Components/Nav/SkinDetail.scss
  src/Components/Nav/SkinSideBar.js
  src/Components/Nav/SkinSideBar.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/Signup.js
  src/Pages/Main/Components/Appointment/Appointment.js
  src/Pages/Main/Components/CitrusFeed/CitrusFeed.js
  src/Pages/Main/Components/Store/Store.js
  src/Pages/Product/Productdetails.js
  src/Pages/ProductList/ProductList.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#7 [송수호] modify: 회원가입 철자 오류 수정완료, 메인페이지 이동 불가 수정중
  .vscode/settings.json
  public/data/PD.json
  public/data/PL.json
  public/data/maindata.json
  public/data/mocup.json
  public/data/productlist.json
  public/data/recommend.json
  src/Components/Productfilternav.js
  src/Pages/Login/Login.js
  src/Pages/Login/Signup.js
  src/Pages/Login/Signup.scss
  src/Pages/Login/test.js
  src/Pages/Main/Appointment.js
  src/Pages/Main/Appointment.scss
  src/Pages/Main/CitrusFeed.js
  src/Pages/Main/CitrusFeed.scss
  src/Pages/Main/Footer.js
  src/Pages/Main/Footer.scss
  src/Pages/Main/ItemSlide.js
  src/Pages/Main/ItemSlide.scss
  src/Pages/Main/Nav.js
  src/Pages/Main/Nav.scss
  src/Pages/Main/Quote.js
  src/Pages/Main/Quote.scss
  src/Pages/Main/Store.js
  src/Pages/Main/Store.scss
  src/Pages/Product/Productdetails.js
  src/Pages/ProductList/ProductList.js
  src/Pages/Productmap/Component/Mapcategoryinfo.js
  src/Pages/Productmap/Component/Mapcategoryinfo.scss
  src/Pages/Productmap/Component/Mapcomponent.js
  src/Pages/Productmap/Component/Mapcomponent.scss
  src/Pages/Productmap/Component/Mapgood.js
  src/Pages/Productmap/Component/Mapgood.scss
  src/Pages/Productmap/Component/Mapgoods.js
  src/Pages/Productmap/Component/Mapgoods.scss
  src/Pages/Productmap/Component/Underbar.js
  src/Pages/Productmap/Component/Underbar.scss
  src/Pages/Productmap/Mapcomponent.js
  src/Pages/Productmap/Maplist.js
  src/Pages/Productmap/Maplist.scss
  src/Routes.js
  src/config.js
Labels: Status: 추가 기능 구현중

#9 [최운정] Refactor : 최종 완성
  public/data/maindata.json
  src/Components/Cart/Cart.js
  src/Components/Cart/Cart.scss
  src/Components/Cart/CartList.js
  src/Components/Cart/CartSum.js
  src/Components/Nav/Nav.js
  src/Components/Nav/SkinSideBar.scss
  src/Components/Productfilternav.js
  src/Pages/Login/Login.js
  src/Pages/Login/Signup.js
  src/Pages/Product/Components/OverlayIngredient.scss
  src/Pages/Product/Productdetails.js
  src/Pages/ProductList/ProductList.js
  src/Pages/Productmap/Maplist.js
  src/config.js
Labels: Status: 리뷰 요청
